### ISSUE TITLE
[Miscellaneous]: Show the View POS option in the My Account > Dashboard menu screen

### ISSUE THREAD

**Issue by tanjiralmamun** [weDevsOfficial/wepos#131]
**Description of the enhancement:**
In my opinion, showing the `View POS` option in the **My Account > Dashboard** menu screen is more user-friendly than showing that option as a **My Account** page menu.

`Suggestion:` https://snipboard.io/cHrazZ.jpg

**Comment by devAsadNur** [comment]
The issue has be resolved by this PR:
* https://github.com/weDevsOfficial/wepos/pull/95
