### ISSUE TITLE
Tax calculation issue with discounts

### ISSUE THREAD

**Issue by CatalystDirections96** [weDevsOfficial/wepos#136]
What we can see happening, if we add a discount to an order in WePOS it shows a subtotal with included Tax. But then the discount is added after that to give a final total.

However, that same order when viewed in WooCommerce Orders, show the discount BEFORE the subtotal and tax is calculated and the final total is then different to the final total shown in WePOS.

See screenshots for example.

In the example, the order in WePOS has a subtotal of $127 and shows that $11.54 in tax is included in that sub total.
It then shows a discount of $7 and a final "Pay Now" total of $120.

If we view the same order in WooCommerce Orders we see the discount is shown first, and then a subtotal of $115.46 with $10.84 tax included.
And the final order total is $119.30. 

**WePOS:**
![WePOS Screenshot](https://github.com/weDevsOfficial/wepos/assets/141790058/9ca4a829-f147-4f46-9944-47f845dd9927)

**WooCommerce:**
![WooCommerce Screeshot](https://github.com/weDevsOfficial/wepos/assets/141790058/998be809-90f6-4012-b78a-ba9ab93d2d2c)

**Comment by Mohaiminulislam1989** [comment]
@devAsadNur please have a look at this

**Comment by CatalystDirections96** [comment]
@Mohaiminulislam1989 @devAsadNur 

How is this progressing?

**Comment by devAsadNur** [comment]
> @Mohaiminulislam1989 @devAsadNur
> 
> How is this progressing?

Bhai, I'll check and give feedback ASAP.

**Comment by Mohaiminulislam1989** [comment]
@devAsadNur any update on this?

**Comment by devAsadNur** [comment]
@Mohaiminulislam1989 Bhai, a PR has been submitted after solving the issue. We'll release a new version shortly.
