### ISSUE TITLE
Mejora 

### ISSUE THREAD

**Issue by anitasantana1995** [weDevsOfficial/wepos#138]
hola,mi wepos no me permite vender ejemplo queso por Kg en cantidades decimales,si quiero vender de mi tienda física 3.4 kg me dice q el parámetro no está permitido y se debe a que no permite las cantidades con decimales,espero que puedan resolver esto para otras versiones, saludos

**Comment by mrbotvzla** [comment]
si es la unica falla que he visto hasta ahora seria genial mejorarlo

**Comment by Mohaiminulislam1989** [comment]
@devAsadNur kichu ekta koro.

**Comment by devAsadNur** [comment]
> @devAsadNur kichu ekta koro.

Ok Bhai, I'll give you feedback soon after doing analysis.

**Comment by devAsadNur** [comment]
@anitasantana1995 @mrbotvzla Gracias por su solicitud sobre este tema. En realidad, la cantidad de números flotantes no es compatible con la mayoría de las plataformas de comercio electrónico, incluido WooCommerce. Por lo tanto, debe crear un producto personalizado por separado para vender la cantidad flotante completa. Por ejemplo, para vender 3,4 KG de un producto es necesario crear un producto independiente y el título del producto debe contener la cantidad. Debe vender 1 cantidad por los 3,4 KG completos de producto. Gracias de nuevo.
