### ISSUE TITLE
Admin bar is showing! 

### ISSUE THREAD

**Issue by nayemDevs** [weDevsOfficial/wepos#20]
Admin bar is disabled for the vendor in Dokan settings but when the vendor is viewing wePOS on the frontend the admin bar appears. That means wePOS is overriding Dokan admin bar settings.

**Comment by littlemystery** [comment]
Hello, I am not using Dokan but using wePOS. When I log out from admin I can see on site admin bar. When I deactivate wePOS, admin bar will disappear.

**Comment by shabnam611** [comment]
Hello @littlemystery,

We have solved this issue already. Kindly install the latest version of the wePOS plugin- https://wordpress.org/plugins/wepos :)

Thank you!
