### ISSUE TITLE
Page not Found when click View Pos

### ISSUE THREAD

**Issue by KingTheLjar** [weDevsOfficial/wepos#26]
I Install wePos on WP . Active it. But when I click View POS it show not found.

**Comment by shabnam611** [comment]
Hello @KingTheLjar,

Please email us at support@wedevs.com so that discuss the issue :) 

Thank you for your understanding!

**Comment by sabbir1991** [comment]
Hi @KingTheLjar,

Please save your permalink settings from admin dashboard and check again.

**Comment by wolfred24** [comment]
Same issue here, page not found, I'm using WordPress with woocomerce on hostinger
