### ISSUE TITLE
VAT field

### ISSUE THREAD

**Issue by littlemystery** [weDevsOfficial/wepos#28]
Is it possible to ad VAT number field into Customer registration form in WePOS? Field connected to WooCommerce EU VAT plugin?

**Comment by sabbir1991** [comment]
Hi, @littlemystery 

Currently *wePOS* is not integrated with WooCommerce EU Vat plugin. Also *wePOS* doesn't add any vat field into customer registration form right now.

However, if we get more request for such kind of feature, then we will think to develop this feature in near future. 

Thanks for your suggestions
