### ISSUE TITLE
Please Help 

### ISSUE THREAD

**Issue by ItsDavehere** [weDevsOfficial/wepos#30]
Php Version 5.6
using xammp locally 
Problem: when I open wepos 
I face this issue 
"
Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404
localhost
Apache/2.4.26 (Unix) OpenSSL/1.0.2l PHP/5.6.31 mod_perl/2.0.8-dev Perl/v5.16.3"

**Comment by sabbir1991** [comment]
Hi @ItsDavehere 

Have you downloaded from wp.org or clone from github ? 

If you had downloaded from wp.org, then please save your permalink settings in `Dashboard -> Settings -> Permalinks` and check again if you faces those errors again.

If you cloned from github. Then navigate to the plugin folder using terminal and run `npm install` and then run `npm run dev` or `npm run build` and then save permalink like above and check again if you found any problem then please let me know. 

Thanks
