### ISSUE TITLE
Rupee Symbol not rendering.

### ISSUE THREAD

**Issue by bamne123** [weDevsOfficial/wepos#31]
Rupee Symbol is not rendering.

![Screen Shot 2019-07-18 at 1 05 20 PM](https://user-images.githubusercontent.com/10872173/61438707-b4b00d00-a95d-11e9-9a6f-e170fed1a4cd.png)

**Comment by bamne123** [comment]
Hi @shabnam611 ,

Symbol is not rendering on complete pos.

![Screen Shot 2019-07-18 at 3 19 37 PM](https://user-images.githubusercontent.com/10872173/61447982-a66aec80-a96f-11e9-8aff-991e28df9904.png)

![Screen Shot 2019-07-18 at 3 19 49 PM](https://user-images.githubusercontent.com/10872173/61447985-a9fe7380-a96f-11e9-9f40-0f878f1460e0.png)

**Comment by sabbir1991** [comment]
Hi @bamne123 

*wePOS* not supported fontawesome. We are using Flaticons for icons and symbols. If you have been changed your currency from WooCommerce settings in backend, I think its automatically render your currency.

Thanks
