### ISSUE TITLE
Addition of payment options other than Cash

### ISSUE THREAD

**Issue by riyaz7us** [weDevsOfficial/wepos#32]
Hi, I don't see any option to add another form of payment such as "credit card" at checkout. Please add one if possible or your advice for another way to do it would be appreciable.
![wepos](https://user-images.githubusercontent.com/32412620/61911780-0821ec80-af56-11e9-83b5-f20013c6bf91.png)

**Comment by nayemDevs** [comment]
@riyaz7us The free version does not have a credit card payment gateway. We will add credit card option into our paid version of wePOS which will be released very soon.

**Comment by riyaz7us** [comment]
Will the paid version have one time payment or monthly subscription?
