### ISSUE TITLE
Please make responsive

### ISSUE THREAD

**Issue by cesarrss** [weDevsOfficial/wepos#41]
Some vendor needs to work in mobile devices, and right now for cell phones it's, absolutely weird.

i think, that some changes in css should be fine
like
@media screen and (max-width:790px){
	#wepos-main {
    display: table-row;
}
	#wepos-main .content-cart .cart-panel .cart-content table.cart-table {
    height:fit-content;
}
	#wepos-main .content-cart {
    min-height: 200px;
}
}

**Comment by stefanusdc07** [comment]
Hello, 
How i can change this css code?
