### ISSUE TITLE
Discount Issue

### ISSUE THREAD

**Issue by lazardanlucian** [weDevsOfficial/wepos#49]
Hello, I have a problem with discounts,
They are only added to subtotal, not to tax aswell.

Example : Product = 5currency , tax = 1.9% -> 0.95 currency:
After applying discount(percentage or not) 1currency for e.g.:

Subtotal : 4currency, tax = 0.95currency

e.g. 50% discount:

Subtotal: 2.5currency, tax = 0.95currency

In my opinion this is not how it should work.
(at least in my country the price is variable, so:
if you sell a thing at 20$, the VAT is x of 20$
if you sell the same thing at 10$ the VAT s x of 10$

**Comment by lazardanlucian** [comment]
![image](https://user-images.githubusercontent.com/34769197/85206627-0d391880-b32c-11ea-8fb5-23cc17ebec0e.png)
I'm seeing now you apply a reverse fee, i looked to all discounts to no avail.

Anyway, as you see, the tax is not updated, so in this case, the reverse fee (discount) should be split, by the tax. so the discount total = 25 / tax percentage, total_tax => total * tax percentage

**Comment by Renny19890** [comment]
Hi.
How can I create a coupon in woocommerce dashboard and works for all vendors?
When I create a coupon I get this message when I apply my coupon code:
A coupon must be restricted with a vendor product.
(Think is like I want to make a discount for all products from my commission)
{If I have 25% commission I’d like to make a coupon for vendors products with 25% coupon or gift code}
How Can I solve it?
Thanks

**Comment by TheIndianGroceryStore** [comment]
I also have the same question as ( @Renny19890 )

If able to use the same coupon system as Woocommerce, it will be easy and flexible to calculate discounts, e.g. volume based on individual items, etc.

**Comment by joseph-sx** [comment]
Same issue as @TheIndianGroceryStore , the coupon does not apply with woocommerce business rules like
Excluded Categories.

I'm using free version.
