### ISSUE TITLE
Bookings and Subscriptions

### ISSUE THREAD

**Issue by raghuvirkonanki** [weDevsOfficial/wepos#81]
Hi Team, 

Does WePOS use the Dokan PRO backend - and leverage products: Booking and Subscription products included and show them on WePOS? Or does WePOS have a separate DB and you'll need to recreate the entire product set again separately for WePOS - assuming that it is the same store that is hosted on the marketplace, that will now be using the WePOS too ! I ask the question since it is not clear from your entire documentation.

**Comment by xaviranik** [comment]
You can use wePOS as a standalone plugin along with WooCommerce. We are planning to integrate wePOS with Dokan to the full extent. wePOS does not have a separate database for products. Instead, wePOS uses WooCommerce products. Kindly let me know if I can help further.
