### ISSUE TITLE
Variable product's attributes are not saved/displayed in order

### ISSUE THREAD

**Issue by mithublue** [weDevsOfficial/wepos#97]
When an order with a variable product is placed, the attributes are not displayed in order detail page. Maybe the attributes are not being saved or not being displayed
![a40d5045-dfd3-47ef-a187-5e8463d7b4bc](https://user-images.githubusercontent.com/9393825/149191890-0b22a10b-865d-412b-8d94-4e2896e1dbfc.png)
![cfc1c861-c55f-49d1-ad2b-69cd53b89871](https://user-images.githubusercontent.com/9393825/149191921-fe88ff4b-86a0-425b-ab60-08be14be1d54.png)
In sreenshot#1, the color and logo info are missing which were supposed to be like screenshot#2.

**Comment by devAsadNur** [comment]
The issue seems invalid. Variable product's attributes are saving and displaying correctly.
